### ISSUE TITLE
Support custom tag indicators

### ISSUE THREAD

**Issue by 1xPdd** [novoid/filetags#26]
Hi:

This seems like a very useful project. I certainly hope to fit it into my workflow. I was wondering if it would be possible to support custom tag formats/indicators. I've been borrowing the `#` to indicate tags and I've seen others use `@`. It would be great to be able to use this script in order to name a file like this:

`filename #tag1 #tag2.txt`

Above all, this visually distinguishes (for me anyway) tags from other parts of the filename. I would also make it possible to search specifically for tags, rather than just something with that word in its title, while not throwing out the simplicity of your system.

Anyhow, thanks!

**Comment by novoid** [comment]
I totally can relate to this request and I understand the advantages of having tags anywhere within a file name, prepended with the famous hashtag character.

Unfortunately, there are several issues that relate to that.

# Comment Character

The `#` character is used as a comment indicator for shell scripts. Therefore, users of any shell would need to quote this character everywhere. To copy a file, you would need to type `cp 2020-02-08\ foo\ \#bar.txt destination/"`.
This is a _weak argument_, because spaces need to be escaped as well and modern shells such as `zsh` are happily offering auto-escaping on TAB-completion.

# Implementation Effort

In the early stage of this project, the file name convention `<filename><separation string><list of tags>.<extension>` was defined. Changing that to "tags may appear anywhere and are prepended by the `#` character" would have a major impact on a majority of code here.
Although I tried to separate logical parts such as "retrieving tags from a given file name" into functions, this is quite some work.

# Logical Implications

I'm using `filetags` on a daily basis myself. I add, remove, switch tags all the time. With the concept as it is, **the order of the tags does not have any semantic meaning** at all. You will get no different results for `foo bar -- tag1 tag2.txt` in comparison to `foo bar -- tag2 tag1.txt`. Including TagTrees and other tools from my concept such as `appendfilename`.
With your proposed change, this would change completely. Imagine, you're applying "remove tag #vienna" and "add tag #graz" on file `2020-02-08T12.09.58 Breakfast with #aunt Sally in #vienna with #schnitzel and #gugelhupf.jpeg`. This would mess up the meaning of your file name since you end up with `2020-02-08T12.09.58 Breakfast with #aunt Sally in with #schnitzel and #gugelhupf #graz.jpeg`.
The alternative would be to add functionality like "replace #vienna with #graz on the same position" or similar. If you think of the set of things you would need to take into account, your head would explode. At least mine would. ;-)

From my perspective, it's the logical implications that are the reason why I can't commit to this change request. Therefore, I'll close this for now.

Of course, if you have further ideas in that direction, feel free to add your comments below!
