### ISSUE TITLE
Introduce TAG_EXTENSION_SEPARATOR to support TagSpaces name scheme

### ISSUE THREAD

**Issue by de-ramon** [novoid/filetags#27]
Hi Karl,

You defined `<filename><separation string><list of tags>.<extension>`.  Using the vars
```
FILENAME_TAG_SEPARATOR = ' -- '
BETWEEN_TAG_SEPARATOR = ' '
```
I'm already able to choose a differnt seperator like your " -- ". That's fine.

But my wife does work on GUI only, so she's more a user of https://www.tagspaces.org/.
They use the scheme `<filename>[<list of tags>].<extension>`
I tried to implement this into the source code and filetags did write the tags in that way, but I didn't get the 
```
# file names containing tags matches following regular expression
FILE_WITH_TAGS_REGEX = re.compile("(.+?)" + FILENAME_TAG_SEPARATOR + "(.+?)(\.(\w+))??$")
```
recognize existing tags.

What do you think about this enhancement? You know your code: Is it easy to implement this feature stable? If yes, I'll try it again. In additon, a .filetags.cfg file holding the vars would be useful for that case.

Thanks for your work,

Ralf

**Comment by novoid** [comment]
Hi Ralf,
A tough question to me. Not just because of `filetags`. Meanwhile, the syntax caught on with many other projects, re-using this decision.
So in the initial implementation, I tried to keep the separator strings in a state where they might be changed. Later on, more and more situations arose where I had to make a decision that I won't change the syntax any more. For example when it comes to TagTrees, some special characters are not allowed, and so forth.
From my perspective, there won't be any support for a different tag separation string. It would limit the other tools in this ecosystems: https://karl-voit.at/demo-filetags-intro/
But hey, it's open source. Feel free to fork and implement it the way you need it to be.

**Comment by de-ramon** [comment]
Hi Karl,
I already forked the script, now it's my turn ;-)

> It would limit the other tools in this ecosystems: https://karl-voit.at/demo-filetags-intro/
Hmm, do you think the chars / symbols [ ] around the tags would limit the other tools? I've to patch them, too, but that should also be possible?!

As already written: I like the shell / text tools very much (grml-user), but I'm also "forced" to use TagSpaces... so I've to get the stuff done.

**Comment by novoid** [comment]
> Hmm, do you think the chars / symbols [ ] around the tags would limit the other tools? I've to patch them, too, but that should also be possible?!

It's worth a try. At first, I was cautious to keep those strings nice and clean. I can hardly give you an estimation. Maybe, it's pretty straight-forward. Wherever possible, adapt the unit tests before (search/replace) so that you get good feedback.
In any case, let me know how it went.

> grml-user

Hehe. I know the people behind grml in person. Yes, this is an awesome Swiss army knife.
