### ISSUE TITLE
Difference with other search tools

### ISSUE THREAD

**Issue by Gahamelas** [novoid/filetags#32]
I was thinking how the -tagtrees capability differs from other search tools. Because as I see it, what this does is search for words in the file names. Using for instance, in mac name:WORD in FINDER's search achieves the same purpose (?). It will retrieve a list of files containing that tag in their file names, by frecency. Please, let me know if I got it wrong. Thanks in advance!

**Comment by novoid** [comment]
The main difference is that filetags is providing a method for navigation, not search. Those are two different concepts of retrieving local files but do have completely different cognitive backgrounds, trying to do the very same: file retrieval.
TagTrees allow for step-by-step narrowing by following different tag branches - just like live-previews adapt to search query extensions.
So if you're happy with filename search and you don't see any advantage with navigation, you probably won't find TagTrees helpful. In my case, I do enjoy browsing through a big pile of clipart photographs within a TagTree in order to find a suitable background image for slides, for example.
I'm going to close the issue for now. However, I can go into details if you like as I do have some research background on this topic: https://karl-voit.at/tagstore/en/papers.shtml

**Comment by Gahamelas** [comment]
This is great. Difference between navigation versus mere search. Thanks!

**Comment by novoid** [comment]
Well, to be precise, the concept of TagTrees is a hybrid between search and navigation with a practical dominance on the navigational side.
For the user's perspective, it's just an additional offer for retrieving tagged files. I would not start to tag just because you want to use TagTrees. However, when you tag files anyway, why not try out these possibilities? At least I'm thinking that TagTree navigation provides me an additional advantage I would not get otherwise.

**Comment by Gahamelas** [comment]
Thanks, I understand that for `filetags --tagtrees` to work the files must have the tags specified in your own way (`- tag1 tag2 tagn`). It wouldn't use the names of the file before the "-", am I correct? Thank you.

**Comment by novoid** [comment]
Correct: filetags does not deal with anything before the tag separator string. If you are interested in tool that help with the datestamp or the file name part before the separator, please take a look at https://karl-voit.at/managing-digital-photographs/

**Comment by Gahamelas** [comment]
Thanks for the quick message! Got it.
