### ISSUE TITLE
Naming pattern

### ISSUE THREAD

**Issue by github-account1111** [novoid/filetags#37]
I am currently setting up filetags, but want a slightly different naming scheme for my files:

`20211224-tag1-tag2--thesis-proposal.org`.

1. Filename length often comes at a premium so date is `YYYYMMDD` saving 2 chars.
1. Tags are between date and filename so that they 1) align (since I don't use time) and 2) are immediately visible.
1. Tags are separated from the filename by `--` saving 2 more chars.
1. I realize special characters are mostly a non-issue today, but I am kinda OCD about them so decided to stick to `a-z`, `0-9` and `-` (I've used `_` instead of `-` in the past, but it was largely a failure because for whatever reason it's not considered a word separator on Windows) - this last one is obviously out of scope and is mostly there to add context to my reasoning.
I have a separate script to take care of that which strips all special characters and transliterates where appropriate.

My question is, is this achievable through minimal variable modification, or would it require some major rewriting and logic changes?

Of course please feel free to tell me if any/all of my changes are bad and why.

**Comment by github-account1111** [comment]
I should've noted that 4. is obviously out of scope and is mostly there to add context to my reasoning.
I have a separate script to take care of that which strips all special characters and transliterates where appropriate.

**Comment by novoid** [comment]
Hi,

Your requirements are valid but different from mine.

You might be interested in looking at https://github.com/novoid/filetags/pull/30 which implemented a different syntax scheme.
As far as I remember I was trying to keep the separating string defined on just one line. However, as I settled for the file name scheme and added more and more tools besides filetags that handle the same file name convention, I did not continue trying to keep the naming scheme separated from the functionality. So my guess would be that this is not trivial change.

Since you ask me for feedback to your requirements:

Length: I value ISO compatibility higher than short file names. I was using YYYYMMDD before and renamed everything accordingly.

Until a decade ago, I was also using `a-zA-Z0-9_-`. Currently, I'm using everything including special characters like € characters and so forth. Modern interactive shell tools support special characters and escaping that good that I don't care to complicate my life so that I serve the computer well.

**Comment by github-account1111** [comment]
Thanks for the feedback! I will keep this part:

>my guess would be that this is not trivial change

in mind.
That looks like a fairly hefty PR.

>Modern interactive shell tools support special characters and escaping that good that I don't care to complicate my life so that I serve the computer well

This is a good point and serves to show that, as I mentioned above, my desire to keep the character set minimal doesn't stem from rationality per se, but more so from a sort of  "OCD" mindset.
Maybe it just looks more pretty to my simple brain haha
I will sleep on this one honestly, maybe I'll follow your suit and embrace all the weird special characters.

Regarding the date format:
YYYYMMDD [seems to be ISO-compliant too](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates), but I may be wrong.

**Comment by novoid** [comment]
Hi,

You're right. The short form is an allowed alternative to YYYY-MM-DD. I prefer the latter because it can be **much** easier parsed by my eyes.

And: if you're _really_ into it, you should call it CDO, as it is supposed to. ;-) (SCNR)

Happy Xmas from Austria!
