### ISSUE TITLE
update pypi with newest version 

### ISSUE THREAD

**Issue by terxw** [novoid/filetags#47]
Hi, would it be possible to update pypi package with newest version?

**Comment by nbehrnd** [comment]
While there is documentation for how to install filetags without pypi, and how to use (currently a little bit lagging) assistance by pypi, one equally may use a third option (at least if you may use Linux) of both worlds:

+ run the installation engaging pypi.org
+ determine where `filetags` now resides.  In my case (Linux Debian), `which filetags` resolves with `/usr/local/bin/filetags`.  Then substitute this file `filetags` (no file extension) with `__init__.py` provided by filetags here on GitHub (don't forget to rename the file).

Because there are no additional dependencies since the release by [2021-04-21 Wed], this works /good enough/.

**Comment by novoid** [comment]
filetags-2022.9.16.1-py3-none-any.whl is uploaded now.

Thanks for the reminder.

To be honest, I don't eat my own dogfood: I have linked the raw Python file in my ~/bin/... and therefore I lack personal motivation for generating the pypi packages which is a bummer. Whenever there is a substantial change, I tend to update pypi.
