### ISSUE TITLE
[Help] Running filetags manually vs. passing as argument for another terminal window

### ISSUE THREAD

**Issue by DeutscheGabanna** [novoid/filetags#62]
Hi,
there's a strange difference in behaviour of filetags I'd like to point out.
If you run it manually, by typing: `filetags` (disregard the lack of arguments for now) - it works fine.

But when you attempt to run a script like this:
`/usr/bin/kgx --command="/bin/bash -i filetags"`
which tries to open a new terminal and type the `filetags` command automatically - it never works.

It returns this:
```
bash: PROG_VERSION: command not found
bash: from: command not found
bash: filetags: line 33: syntax error near unexpected token `('
bash: filetags: line 33: `def save_import(library):'
```

Even on this newly opened terminal, it only works if I type the command manually - `filetags` - then it works.

**Comment by DeutscheGabanna** [comment]
Solved. `filetags` does not inherit some environmental variables from a newly-generated terminal. This helps:
`/usr/bin/kgx --command="/bin/bash -i -c 'source ~/.bashrc && filetags'"`

**Comment by novoid** [comment]
For reference: filetags is not a shell script. filetags is implemented in the Python programming language.

Therefore, it's not invoked via `/bin/bash (-i) filetags`, it's invoked either directly (so the shebang defines the Python interpreter to use) `(/path/to/)filetags` or via `(/usr/bin/)python filetags` command.

Your error message above lists bash errors because the bash shell is not able to interpret Python source code.

I don't know kgx but I assume that `/usr/bin/kgx --command="filetags"` or `/usr/bin/kgx --command="(/path/to)python3 (/path/to/)filetags"` or similar would have worked.

As a side-remark, I'd recomment to invoke Python tools like filetags via venv. In my case, this is wrapped in a shell script like that:

```
bin % cat ~/bin/filetags 
#!/usr/bin/env bash
/home/$USER/src/filetags/venv/bin/python ~$USER/src/filetags/filetags/__init__.py "$@"
#end
bin % 
```

HTH
