### ISSUE TITLE
Few questions about filetags for TagsResearch

### ISSUE THREAD

**Issue by Qronikarz** [novoid/filetags#71]
> Send feature wishes or improvements as an issue on GitHub

Hopefully questions can also be asked. If not, you can just close this issue.

First of all. I'd like to thank you for your excellent article on the tagging situation on Windows. I don't use Windows since few years so having such detailed writing to confirm my past problems was like a gift.

I also didn't connect the dots that you have also made the tool that I added to TagsResearch collection and only discovered that few days ago while trying to read all your articles on tagging files.

So now for questions if I may.
1. Is there any order that you recommend to get through all your file tagging articles? I got kind of lost and would like to do a total read from the beginning. Possibly without watching videos since I prefer written media.
2. Would you be interested to take a look at my TagsResearch and offer some criticisms? There's also filetags.md entry which would be good to be proof checked by the actual developer. The entry is not actually finished since I had a rule that if I'm not certain about availability of some feature then it can't be filled to not make fake claims.
Of course that's only if you have time for checking it. It's a general collection of categorized programs that specialize in tagging of various items and 2 short articles that offer advantages and disadvantages of tagging. (it's on my GitHub if you're interested)
3. --filter Does it work only with Boolean AND? And is there an option to exclude certain tags from the search?

**Comment by nbehrnd** [comment]
> 1. Is there any order that you recommend to get through all your file tagging articles? I got kind of lost and would like to do a total read from the beginning. Possibly without watching videos since I prefer written media.

Taking the perspective of a user I would recommend to start with date2name
because its documentation links to a video recording of «The Advantages of
File Name Conventions and Tagging».[1]  It is both an appetizer and a swift
demonstration of what the tools offer; only 45 min which don't feel long
(quite the contrary).

From there, with the focus on application of tags, there are three blog posts
I consider as a 101 to get started, namely

+ «How to Use Tags» (https://karl-voit.at/2022/01/29/How-to-Use-Tags/), basics
+ «Managing Digital Files (e.g., Photographs) in Files and
  Folders»
  (https://karl-voit.at/managing-digital-photographs/) as an example of application, and
+ «My Folder Hierarchy» (https://karl-voit.at/folder-hierarchy/)

There are a couple of reasons why (in my opinion) the third one should be read
early, perhaps especially because of the tree diagram to illustrate the
approach.  For me, it took some time / multiple uses to recognize the advantage
to create an archive directory of which `events_memories` as a mezzanine-like
sub folder of which each year is the sub sub folder of the archive.

Second -- though tempting to the novice -- not every thing and file is equally
well suitable for the set of `date2name`, `filetags` and eventually
`move2archive`.  In Karl's example, it is for instance a collection of .mp3
files.  For me, (academic) papers as .pdf files are better organized with a
reference manager like zotero (though tagging with a controlled vocabulary
equally is useful there).  Projects managed by git (or other version control
systems) equally are better organized outside the `filetags` moderated
archive, too -- which often is source code, but equally may be reports (.tex,
.org, .md).

Eventually, it is up to you/your preferred workflow which modular tool(s) to
engage -- sometimes as provided, other times with an adjustment to suit your
needs.  This indeed can yield e.g., two shortcuts both in Thunar (a file
browser) and geeqie (an image viewer) to let `date2name` either add only the
day, or both day and time of creation to a file's name.  Aside from the
recommendations «related articles» below the blog posts, I didn't recognize a
strictly linear (curriculum-like) sequence to read.

[1] mirrored on youtube: https://www.youtube.com/watch?v=rckSVmYCH90

**Comment by novoid** [comment]
@nbehrnd I'm really puzzled. I could have written that comment myself. Thanks for jumping in so fast.

Consider me deeply impressed.

**Comment by novoid** [comment]
> First of all. I'd like to thank you for your excellent article on the tagging situation on Windows. I don't use Windows since few years so having such detailed writing to confirm my past problems was like a gift.

Hehe, you're welcome.

> I also didn't connect the dots that you have also made the tool that I added to TagsResearch collection and only discovered that few days ago while trying to read all your articles on tagging files.
> 
> So now for questions if I may.
> 
>     1. Is there any order that you recommend to get through all your file tagging articles? I got kind of lost and would like to do a total read from the beginning. Possibly without watching videos since I prefer written media.

See posting from @nbehrnd 

>     2. Would you be interested to take a look at my TagsResearch and offer some criticisms? There's also filetags.md entry which would be good to be proof checked by the actual developer. The entry is not actually finished since I had a rule that if I'm not certain about availability of some feature then it can't be filled to not make fake claims.
>        Of course that's only if you have time for checking it. It's a general collection of categorized programs that specialize in tagging of various items and 2 short articles that offer advantages and disadvantages of tagging. (it's on my GitHub if you're interested)

https://github.com/Qronikarz/TagsResearch/blob/main/components/filetags.md

"Files tag manager" -> I don't know the other options here but I would not consider filetags as some kind of manager.

"Website" -> I'd vote for https://karl-voit.at/managing-digital-photographs/ which I'm using as a general motivation which motivates and summarizes the basic concept.

"Supported file systems" -> FS independent/agnostic

"Required dependencies" -> Python3

"Written in" -> You should switch to Python3 since it more or less doesn't work with Python2 any more and Python2 support is not available any more.

"Language support" -> English

"Dark mode" -> depends on the chosen interface (Terminal emulator)

"Tag support links" -> I don't understand.

"Tag groups" -> no

"Tag colors" -> no or done via shell

"Exclude tags from search" -> no

"Tag blocking" -> I don't understand.

"Tag deleting" -> yes

"Tag aliases" -> no

"Tag implications" -> I don't understand

"Tag descriptions" -> as comments in the tag definition files (controlled vocabularies, `.filetags`)

"Tag statistics" -> I've got tag gardening which may qualify here

"Hidden tags" -> No

"Tagging with AI" -> :clown_face: 

"Cloud saving" -> I don't understand or it's "no"

"Search view types" -> you may want to add TagTrees which is a great feature you may not find elsewhere

I hope, that helps.

You may be interested in https://karl-voit.at/tagstore/ and my PhD on https://karl-voit.at/tagstore/en/papers.shtml - the PhD PDF mentions some interesting tag- and non-tag-related PIM tools in its first chapters.

Note that I was using tagstore (concept + research platform) for doing research for my PhD. It's also a Python tool but with a GUI for flexible changing its tagging capabilities to test different aspects around tagging. It's FOSS: https://karl-voit.at/tagstore/en/download-disclaimer.shtml

After finishing my PhD, I developed the idea further into my filetags concept I'm using myself on a daily basis.

Just to give you some context.

>     3. --filter Does it work only with Boolean AND? And is there an option to exclude certain tags from the search?

No, there isn't. I personally do that via "[...] | grep -v" in certain situations.

I'll close this ticket for now. Feel free to post further messages, we don't need an open issue for that.

**Comment by Qronikarz** [comment]
> "Files tag manager" -> I don't know the other options here but I would not consider filetags as some kind of manager.

Generally just a very short description what the program is. Some options are "file browser", "media board", "bookmark manager". I had a problem classifying filetags so took some words from filetags GitHub description. It allows for renaming the files with tags, but also then allows to search them so it's not just a renaming utility. Maybe "tagging tool"?

> "Tag support links" -> 

This was an entry mostly for programs that didn't have tag support since the beginning. So if tagging functionality was added later there is generally some news article about it. Or in the case of Linux file browsers there are feature requests and forum links where users or even devs shared their opinion about adding this feature.

> "Tag blocking" ->

In single user programs a rare feature but in some web programs that are then offered to multiple users, they can select to not show any items/files tagged with certain tags. So tl;dr a tags blocklist.

> "Tag implications" -> 

This is something similar to your mutually exclusive tags, but in reverse? Basically one tag implies that another tag should also be applied. Like if you for example tag a photo with "lake" then you should also be able to search for it with "water" tag (since lakes are made of water. Mostly, because there are also lakes of lava)

> "Cloud saving" -> I don't understand or it's "no"

In my opinion I would say it's a yes, but only technically. There are 3 main ways of tagging files - file rename, file metadata, database. Some programs that use a database offer the ability to use cloud to synchronize tags between devices.
While I personally don't like the file rename method I do see the advantages - biggest of which is the outstanding cross platform support. So even if you put your file on an online hosting, your tags stay and you can use them. That's unless filetags depends on the .filetags tag definitions files to work.

> You may be interested in https://karl-voit.at/tagstore/ and my PhD on https://karl-voit.at/tagstore/en/papers.shtml - the PhD PDF mentions some interesting tag- and non-tag-related PIM tools in its first chapters.

I'll check it out. But with your PhD Thesis PDF the expected read time of all your articles just upgraded to few weeks. I may not finish it whole in near future, but I'll keep it saved.

> No, there isn't. I personally do that via "[...] | grep -v" in certain situations.

I'll add a footnote to that entry with that explanation.

> I'll close this ticket for now. Feel free to post further messages, we don't need an open issue for that.

Alright. That's fair.

Thank you to both of you so far.

**Comment by novoid** [comment]
> > "Files tag manager" -> I don't know the other options here but I would not consider filetags as some kind of manager.
> 
> Generally just a very short description what the program is. Some options are "file browser", "media board", "bookmark manager". I had a problem classifying filetags so took some words from filetags GitHub description. It allows for renaming the files with tags, but also then allows to search them so it's not just a renaming utility. Maybe "tagging tool"?

filetags is different in many aspects when compared to other tools, yes.

Due to the fact that my concept just renames files, most categories don't apply here, I guess. So maybe there is need for a "file name modification management" category? That should explain much more because with meta-data in file names, you know exactly that your meta-data is not affected as long as the file name is not changed.

> > "Tag support links" ->
> 
> This was an entry mostly for programs that didn't have tag support since the beginning. So if tagging functionality was added later there is generally some news article about it. Or in the case of Linux file browsers there are feature requests and forum links where users or even devs shared their opinion about adding this feature.

I understand your description but at least I still don't have any clue what that has to do with "tag support links". 

> > "Tag blocking" ->
> 
> In single user programs a rare feature but in some web programs that are then offered to multiple users, they can select to not show any items/files tagged with certain tags. So tl;dr a tags blocklist.

Ah, a block-list of some sorts. I see.

> > "Tag implications" ->
> 
> This is something similar to your mutually exclusive tags, but in reverse? Basically one tag implies that another tag should also be applied. Like if you for example tag a photo with "lake" then you should also be able to search for it with "water" tag (since lakes are made of water. Mostly, because there are also lakes of lava)

I see. To me, such a feature would be a bad idea but I get the point.

> > "Cloud saving" -> I don't understand or it's "no"
> 
> In my opinion I would say it's a yes, but only technically. There are 3 main ways of tagging files - file rename, file metadata, database. Some programs that use a database offer the ability to use cloud to synchronize tags between devices. While I personally don't like the file rename method I do see the advantages - biggest of which is the outstanding cross platform support. So even if you put your file on an online hosting, your tags stay and you can use them. That's unless filetags depends on the .filetags tag definitions files to work.

I'd vote for "tags survive file synchronization" because people like me are not using any cloud at all but they certainly use synchronization tools like Syncthing and such.

> > You may be interested in https://karl-voit.at/tagstore/ and my PhD on https://karl-voit.at/tagstore/en/papers.shtml - the PhD PDF mentions some interesting tag- and non-tag-related PIM tools in its first chapters.
> 
> I'll check it out. But with your PhD Thesis PDF the expected read time of all your articles just upgraded to few weeks. I may not finish it whole in near future, but I'll keep it saved.

You decide how deeply you want to follow in this rabbit hole. :stuck_out_tongue_winking_eye: :rabbit: 

> > No, there isn't. I personally do that via "[...] | grep -v" in certain situations.
> 
> I'll add a footnote to that entry with that explanation.

You could maybe write something like "file management filters apply" which should indicate that CLI shells as well as general file managers can use their filter mechanism if available. My grep method is just one use-case of many that can be applied here.

> > I'll close this ticket for now. Feel free to post further messages, we don't need an open issue for that.
> 
> Alright. That's fair.
> 
> Thank you to both of you so far.

You're welcome. I'll keep your page as a very good reference to tag tools. Thanks for your work here!

**Comment by Qronikarz** [comment]
> Due to the fact that my concept just renames files,

If it was just a rename then "renaming tool" would surely suffice, but filetags has search feature, tag gardening and TagTrees so it's not just a simple renaming tool.

Anyway, I have changed filetags type to what you suggested. Kind of long, but I honestly can't think of anything here and this matches well. The categories aren't set in stone so that's not a problem.

> I still don't have any clue what that has to do with "tag support links".

Perhaps it's too badly shortened on my part. I wanted to keep entries short since their explanation is in glossary anyway. The full name would be something like "links to sites that talk about supporting tagging feature". Doesn't really matter for filetags since it had tagging support from the start.

> I'd vote for "tags survive file synchronization" because people like me are not using any cloud at all but they certainly use synchronization tools like Syncthing and such.

I wanted to say that it's already the "Tags prevail item modification", but no that's not it. I deleted the checkmark from filetags "cloud saving" entry. I need to think about it more. 

> You decide how deeply you want to follow in this rabbit hole. 😜 🐰

I'm already way too deep in this tagging adventure. It was just supposed to be a fun project of making a portable cross-platform media gallery. And here I am with this collection of programs and a need to rewrite my QuoMediaView for supporting all file types, folders, custom items and web bookmarks. But I discovered some great projects so there's at least that.

> Thanks for your work here!

Likewise.
I already updated the filetags.md with information from your 2 posts. It still has some entries to fill in, but it's mainly done (it wasn't really made for CLI programs in mind, so I need to decide on way to fill some entries that depend on terminal emulator - like the dark mode or ).
There are also 3 places that I can fill you in as contributor since you did contribute - the readme.md, filetags.md bottom and a developer fact check at the top. But that's if you want.
